version: '3'
services:
  app:
    build: .
    container_name: data-in-cloud
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: "postgres:14.11"
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=DataInCloud
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo
    ports:
      - "27035:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password


  RabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
